language: haskell
dist: trusty

cache:
  directories:
    - $HOME/.cabal/store

cabal: "2.4"

matrix:
  include:
    - ghc: "8.6.5"

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-build
 - cabal v2-test --enable-test
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated
 - cabal v2-build magic-tyfams
 - cabal v2-build cmptype
 - cabal v2-test --enable-test cmptype

